name: AvertoxVehicles
version: ${project.version}
main: dragonfire.freebuildsystem.Vehcile.AvertoxVehiclesPlugin
api-version: '1.20'
softdepend:
  - Vault
commands:
  vehicle:
    description: Open the vehicle shop
    usage: /vehicle [balance]
    aliases: [vehicles, vshop]
permissions:
  avertoxvehicles.use:
    description: Allows opening and using the vehicle shop
    default: true
